# Replace the text below to customize your site
site_name: Crowd Controller
site_description: Crowd Controller
site_author: Bas Pijls
copyright: Copyright 2024 Bas Pijls

# site_url: https://knowledgebase.hbo-ict-hva.nl
# repo_url: https://gitlab.fdmci.hva.nl/propedeuse-hbo-ict/knowledgebase/student-knowledgebase

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://code.iconify.design/3/3.0.0/iconify.min.js

theme:
  name: material

  # custom_dir: mdocotion
  hide_site_name: true
  content_margin_top: 0px
  icon:
    logo: material/music-note-bluetooth
  

  features:
    - search.share
    - content.code.annotate
    - navigation.sections
    - content.tabs.link
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - mkdocs-video:
      css_style:
        is_video: True
        min-width: "640px"
        max-width: "900px"
        min-height: "360px"        
  - section-index
  - autolinks  
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]
  - exclude-search:
      exclude:
        - 3_onderwijs/*      

markdown_extensions:
  - extra
  - abbr
  - smarty
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md        
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
